# Generated by Django 5.2.11 on 2026-02-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("social_post", "Social Media Post"),
                            ("blog_outline", "Blog Outline"),
                            ("ad_copy", "Ad Copy"),
                        ],
                        max_length=50,
                    ),
                ),
                ("tone", models.CharField(blank=True, max_length=50, null=True)),
                ("generated_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
