# Generated by Django 5.2.11 on 2026-02-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentrequest",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("social_post", "Social Media Post"),
                    ("blog_outline", "Blog Outline"),
                    ("ad_copy", "Ad Copy"),
                    ("essay", "Essay"),
                    ("product_desc", "Product Description"),
                ],
                max_length=50,
            ),
        ),
    ]
